# Generated by Django 4.2 on 2023-05-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ONLINE_SERVICES', 'ONLINE_SERVICE'), ('FOOD', 'FOOD'), ('TRAVEL', 'TRAVEL'), ('RENT', 'RENT'), ('OTHERS', 'OTHERS')], max_length=255),
        ),
    ]
